# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

# Android
# Build a Gradle-based Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

variables:
- group: AppVariables-Common
- group: AppVariables-TD

trigger:
- test/azure-extension-td

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: DownloadSecureFile@1
#   name: keystore
#   inputs:
#     secureFile: 'ac-sample.jks'
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean assembleRelease'
    # options: '-PkeystoreFile=$(keystore.secureFilePath) -PkeystorePassword=$(keystorePassword) -PkeyAlias=$(keyAlias) -PkeyPassword=$(keyPassword)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'ac-sample.jks'
    apksignerKeystorePassword: '$(keystorePassword)'
    apksignerKeystoreAlias: '$(keyAlias)'
    apksignerKeyPassword: '$(keyPassword)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
    flattenFolders: true
- task: CmdLine@2
  inputs:
    script: 'mv $(build.artifactStagingDirectory)/apk-release-unsigned.apk $(build.artifactStagingDirectory)/apk-release-signed.apk'
    # workingDirectory: '$(build.artifactStagingDirectory)'
  displayName: 'Rename APK'
# - bash: |
#     mv "$(build.artifactStagingDirectory)/apk-release-unsigned.apk" "$(build.artifactStagingDirectory)/apk-release-signed.apk"
#   displayName: 'Rename APK'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'ac-sample-artifact'
    publishLocation: 'Container'

- task: AppcircleDistribute@0
  inputs:
    accessToken: '$(ac-pat)'
    profileId: '$(ac-dist-profile-id)'
    appPath: '$(Build.ArtifactStagingDirectory)/app-release-signed.apk'
    message: '$(ac-dist-message)'
