# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

require 'dotenv'
Dotenv.load('.env.common') # specify your environment-specific file
Dotenv.load('.env.td')
Dotenv.load('.env.eas')

platform :android do
  desc "Build and sign the Android app"
  lane :build_signed_apk do
    gradle(
      task: 'clean assemble',
      build_type: 'Release'
    )
  end

  lane :build_signed_aab do
    gradle(
      task: 'clean bundle',
      build_type: 'Release'
    )
  end

  lane :deploy_td do
    # puts "Access Token: #{ENV["AC_ACCESS_TOKEN"]}"
    # puts "Profile ID: #{ENV["AC_PROFILE_ID"]}"
    # puts "App Path: #{ENV["AC_APP_PATH"]}"
    # puts "Message: #{ENV["AC_MESSAGE"]}"

    appcircle_testing_distribution(
      accessToken: ENV["AC_ACCESS_TOKEN"], # Your Appcircle Access Token
      appPath: ENV["AC_APP_PATH"], # Path to your iOS .ipa or .xcarchive, or Android APK or App Bundle
      profileName: ENV["AC_PROFILE_NAME"], # ID of your Appcircle Distribution Profile
      createProfileIfNotExists: ENV["CREATE_PROFILE_IF_NOT_EXISTS"],
      message: ENV["AC_MESSAGE"] # Your Message
    )
  end

  lane :deploy_eas do
      appcircle_enterprise_store(
        accessToken: ENV["AC_ACCESS_TOKEN"],
        appPath: ENV["AC_APP_PATH"],
        # entProfileName: ENV["ENTERPRISE_PROFILE_NAME"],
        # createProfileIfNotExists: ENV["CREATE_PROFILE_IF_NOT_EXISTS"],
        summary: ENV["SUMMARY"],
        releaseNotes: ENV["RELEASE_NOTES"],
        publishType: ENV["PUBLISH_TYPE"] # Assign the appropriate number based on the status: None (0), Beta (1), Live (2)
      )
    end
end
