# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and sign the Android app"
  lane :build_signed_apk do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  lane :build_signed_aab do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end
end
