name: TD

on:
  push:
    branches: [ "test/github-extensions-td-eas" ]
  pull_request:
    branches: [ "test/github-extensions-td-eas" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      
      - name: Decode the keys
        env:
          AC_SAMPLE_JKS_BASE64: ${{ secrets.AC_SAMPLE_JKS }}
          KEYSTORE_PROPERTIES: ${{ vars.KEYSTORE_PROPERTIES }}
          # DOT_ENV: ${{ vars.DOT_ENV }}
        run: |
          # create variables
          mkdir -p $GITHUB_WORKSPACE/keystore
          JKS_PATH=$GITHUB_WORKSPACE/keystore/ac-sample.jks
          PROPERTIES_PATH=$GITHUB_WORKSPACE/keystore/keystore.properties
          
          # write to file
          echo -n "$AC_SAMPLE_JKS_BASE64" | base64 --decode > $JKS_PATH
          echo -n "$KEYSTORE_PROPERTIES" > $PROPERTIES_PATH

      - name: Debug Env.
        run: |
          echo "$RUNNER_TEMP"
          ls $RUNNER_TEMP
          echo "$GITHUB_WORKSPACE"
          ls $GITHUB_WORKSPACE
          
      - name: Build
        run: |
          echo $AC_PP_UUID
          bundle exec fastlane android build_signed

      - name: Appcircle Testing Distribution
        uses: appcircleio/appcircle-testing-distribution-githubaction@v0.0.2
        env:
          AC_ACCESS_TOKEN: ${{ secrets.AC_ACCESS_TOKEN }}
          AC_PROFILE_ID: ${{ vars.AC_PROFILE_ID }}
          AC_APP_PATH: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk
        with:
          accessToken: $AC_ACCESS_TOKEN
          profileID: $AC_PROFILE_ID
          appPath: $AC_APP_PATH
          message: "Hello from Github to TD"

      
